spring:
  application:
    name: zillionchu-sso
server:
  port: 8003

eureka:
  client:
    service-url:
      #defaultZone: http://zillionchu7000.com:7000/eureka
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: zillionchu-sso-8003
    prefer-ip-address: true
    hostname: zillionchu-sso
